#!perl
use utf8;
use Local::Linter::Util;

my $errors = 0;

foreach my $file ( get_all_pods() ) {
	local @ARGV = $file;
	while( <> ) {
		if( /\A \s+ B<<? \s* \$ \s \S /x ) {
			warning( "Possible \$ as shell prompt", $_ );
			$errors++;
			}
		}
	}

exit $errors;

