#!perl
use utf8;
use Local::Linter::Util;

my $errors = 0;

foreach my $file ( get_all_pods() ) {
	local @ARGV = $file;
	while( <> ) {
		next unless /\A =end \s* \z/;
		warning( "Possible explicit Chapter", $_ ) unless $1;
		$errors++;
		}
	}

exit $errors;
