#!perl
use utf8;
use Local::Linter::Util;

my $errors = 0;

foreach my $file ( get_all_pods() ) {
	local @ARGV = $file;
	while( <> ) {
		next if /\A\s/;
		next unless / >> [a-z] \B/x;
		warning( "Lowercase letter after >>", $_ ) unless $1;
		$errors++;
		}
	}

exit $errors;
