#!perl
use utf8;
use Local::Linter::Util;

my $errors = 0;

foreach my $file ( get_all_pods() ) {
	local @ARGV = $file;
	while( <> ) {
		next unless /\A\S .+ N<<? /x;
		warning( "N<< footnote", $_ );
		$errors++;
		}
	}

exit $errors;
