#!perl
use utf8;
use Local::Linter::Util;

my $errors = 0;

foreach my $file ( get_all_pods() ) {
	local @ARGV = $file;
	while( <> ) {
		next unless /I<.*?>\(\d\)/x;
		warning( "Possible styled manpage reference", $_ );
		$errors++;
		}
	}

exit $errors;
