#!perl
use utf8;
use Local::Linter::Util;

my $errors = 0;

my %Overused_words;
while( <DATA> ) {
	chomp;
	$_ = lc;
	$Overused_words{$_}++;
	}

my $pattern = join '|', map "\Q$_\E", keys %Overused_words;

foreach my $file ( get_all_pods() ) {
	local @ARGV = $file;
	while( <> ) {
		next unless / ($pattern) /ix;
		warning( "Possible use of overused word ($1)", $_ );
		$errors++;
		}
	}

exit $errors;

__END__
indeed