#!perl
use utf8;
use Local::Linter::Util;

my $errors = 0;

foreach my $file ( get_all_pods() ) {
	local @ARGV = $file;
	while( <> ) {
		next unless / ( 201\d \. [0-9]{2} ) /x;
		next if $1 eq $ENV{RAKUDO_LATEST_VERSION};
		warning( "Possible use of outdated Rakudo version ($1)", $_ );
		$errors++;
		}
	}

exit $errors;

