#!perl
use utf8;
use Local::Linter::Util;

my $errors = 0;

foreach my $file ( get_all_pods() ) {
	local @ARGV = $file;
	while( <> ) {
		next unless / U<+ (.*?) > /x;
		my $insides = $1;
		next unless $insides =~ / (.*?) \| (.*) /x;

		my( $first, $second ) = ( $1, $2 );

		next if $first =~ m/ \A https? /x;
		next unless $second  =~  m/ \A https? /x;

		warning( "Out of order U<>. The URL goes first", $_ );
		$errors++;
		}
	}

exit $errors;

