#!perl
use utf8;
use Local::Linter::Util;

my $errors = 0;

foreach my $file ( get_all_pods() ) {
	local @ARGV = $file;
	while( <> ) {
		next unless / (?<letter>\w) <<? [^>]+ X<<? /x;
		next if $+{letter} eq 'N';
		warning( "Possible X<< in $+{letter}", $_ );
		$errors++;
		}
	}

exit $errors;
