#!perl
use utf8;
use Local::Linter::Util;

my $errors = 0;

foreach my $file ( get_all_pods() ) {
	local @ARGV = $file;
	while( <> ) {
		next unless /\A =item .*? X< /x;
		warning( "Possible index entry in =item", $_ );
		$errors++;
		}
	}

exit $errors;

