=head0 Chapter Title

This is some text

=head1 Level 1 header

This paragraph has some I<italic text>.

=head2 Level 2 header

This paragraph has some B<bold text>.

=head2 Level 2 header again

Here's a U<http://www.example.com|Example.com> link.

=head1 Another Level 1

Another book I wrote is T<Learning Perl>.

=head2 But a level 2

We're going to see some code now:

    #!/usr/bin/perl
    use v5.10;
    say "Hello world";
    foreach my $number ( 0 .. 100 ) {
        say $number;
        }

Now the code is over and there's a D<item I need to finish>.

This is another paragraph.

=head2 But a level 3

=cut
